export const products = [
  {
    slug: "paket-total-knee-replacement",
    name: "Paket Total Knee Replacement (TKR PS)",
    category: "Knee Stem",
    description:
      "Paket Total Knee Replacement PS yang terdiri dari 1pcs Femoral Component, 1pcs Tibial Insert ,1pcs Tibial Component dan 1pcs Bonecement",
    image: "/img/products/Paket Total Knee Replacement.jpg", 
    noProduct: "BIK230801",
    modelOrType: "Total Knee Replacement",
    unitsOfMeasurement: "Set",
    kbkiCode: "4817104010",
    permitToCirculateNumber: "AKL 21302711493",
    factoryName: "UNITED ORTHOPEDIC CORPORATION",
    productValidityPeriod: "2027-08-23",
  },
  {
    slug: "paket-total-hip-replacement-cemented",
    name: "Paket Total Hip Replacement Cemented (THR CEMENTED)",
    category: "Hip Stem",
    description:
      "Paket THR CEMENTED yang terdiri dari 1pcs FULL XPE Cup,1 pcs Femoral Head , 1pcs U2 Cemented Stem dan 1pcs Bonecement",
    image: "/img/products/Paket Total Hip Replacement Cemented (THR CEMENTED).jpg", 
    noProduct: "BIK230802",
    modelOrType: "Total Hip Replacement Cemented",
    unitsOfMeasurement: "Set",
    kbkiCode: "4817104010",
    permitToCirculateNumber: "AKL 21302711490",
    factoryName: "UNITED ORTHOPEDIC CORPORATION",
    productValidityPeriod: "2027-08-23",
  },
  {
    slug: "paket-total-hip-replacement-cementless",
    name: "Paket Total Hip Replacement Cementless (THR CEMENTLESS)",
    category: "Hip Stem",
    description:
      "Paket THR Cementless yang terdiri dari 1 pcs Cementless Cup, 1pcs Cup Liner,1pcs Femoral head, 1 pcs Cementless Stem dan 3pcs Cancellous Screw",
    image: "/img/products/Paket Total Hip Replacement Cementless (THR CEMENTLESS).jpg", 
    noProduct: "BIK230803",
    modelOrType: "Total Hip Replacement Cementless",
    unitsOfMeasurement: "Set",
    kbkiCode: "4817104010",
    permitToCirculateNumber: "AKL 21302711491",
    factoryName: "UNITED ORTHOPEDIC CORPORATION",
    productValidityPeriod: "2027-08-23",
  },
  {
    slug: "paket-bipolar-cementless",
    name: "Paket Bipolar Cementless",
    category: "Others",
    description:
      "Paket Bipolar Cementless yang terdiri dari 1pcs Bipolar Head, 1pcs Femoral head, dan 1pcs Cementless Stem",
    image: "/img/products/Paket Bipolar Cementless.jpg", 
    noProduct: "BIK230804",
    modelOrType: "Bipolar Cementless",
    unitsOfMeasurement: "Set",
    kbkiCode: "4817104010",
    permitToCirculateNumber: "AKL 21302711299",
    factoryName: "UNITED ORTHOPEDIC CORPORATION",
    productValidityPeriod: "2027-08-29",
  },
  {
    slug: "paket-bipolar-cemented",
    name: "Paket Bipolar Cemented",
    category: "Others",
    description:
      "Paket Bipolar Cemented yang terdiri dari 1pcs Bipolar Head, 1pcs Femoral Head, 1pcs Cemented Stem dan satu 1pcs Bonecement",
    image: "/img/products/Paket Bipolar Cemented.jpg", 
    noProduct: "BIK230805",
    modelOrType: "Bipolar Cemented",
    unitsOfMeasurement: "Set",
    kbkiCode: "4817104010",
    permitToCirculateNumber: "AKL 21302711299",
    factoryName: "UNITED ORTHOPEDIC CORPORATION",
    productValidityPeriod: "2027-08-29",
  },
  {
    slug: "paket-thr-hybrid",
    name: "Paket THR Hybrid",
    category: "Others",
    description:
      "Paket THR Hybrid yang terdiri dari 1pcs Cup cementless, 1pcs Cup Liner, 1pcs Femoral Head, 1pcs cemented stem , 3 pcs Cancellous Screw dan 1 pcs Bonecement",
    image: "/img/products/Paket THR Hybrid.jpg", 
    noProduct: "BIK230801",
    modelOrType: "THR Hybrid",
    unitsOfMeasurement: "Set",
    kbkiCode: "4817104010",
    permitToCirculateNumber: "AKL 21302711491",
    factoryName: "UNITED ORTHOPEDIC CORPORATION",
    productValidityPeriod: "2027-08-23",
  },
  {
    slug: "paket-thr-reverse-hybrid",
    name: "Paket THR Reverse Hybrid",
    category: "Others",
    description:
      "Paket THR Reverse Hybrid yang terdiri dari 1 Cemented Cup, 1 Femoral Head, dan 1 Cementless Stem",
    image: "/img/products/Paket THR Reverse Hybrid.jpg", 
    noProduct: "BIK230807",
    modelOrType: "Reverse Hybrid",
    unitsOfMeasurement: "Set",
    kbkiCode: "4817104010",
    permitToCirculateNumber: "AKL 21302910486",
    factoryName: "UNITED ORTHOPEDIC CORPORATION",
    productValidityPeriod: "2027-08-23",
  },
  {
    slug: "cement-restrictor-full-pe",
    name: "Cement Restrictor Full PE",
    category: "Others",
    description:
      "",
    image: "/img/products/Cement Restrictor Full PE.jpg", 
    noProduct: "BIK230808",
    modelOrType: "Cement Restrictor Full PE",
    unitsOfMeasurement: "piece",
    kbkiCode: "4817104010",
    permitToCirculateNumber: "AKL 21302711558",
    factoryName: "UNITED ORTHOPEDIC CORPORATION",
    productValidityPeriod: "2027-08-29",
  },
  {
    slug: "cement-centralizer",
    name: "Cement Centralizer",
    category: "Others",
    description:
      "",
    image: "/img/products/Cement Centralizer.jpg", 
    noProduct: "BIK230809",
    modelOrType: "Cement Centralizer",
    unitsOfMeasurement: "piece",
    kbkiCode: "4817104010",
    permitToCirculateNumber: "AKL 21302711558",
    factoryName: "UNITED ORTHOPEDIC CORPORATION",
    productValidityPeriod: "2027-08-29",
  },
  {
    slug: "biofix-1g-bonecement",
    name: "BIOFIX 1G Bonecement",
    category: "Others",
    description:
      "",
    image: "/img/products/BIOFIX 1G Bonecement.jpeg", 
    noProduct: "BIK230810",
    modelOrType: "880255",
    unitsOfMeasurement: "piece",
    kbkiCode: "3417012002",
    permitToCirculateNumber: "AKL 31302026319",
    factoryName: "SYNIMED (SYNERGIE INGENIERIE MEDICALE)",
    productValidityPeriod: "2026-09-21",
  },
  {
    slug: "ningbo-disposable-pulse-lavage-surgical-system",
    name: "NINGBO Disposable Pulse Lavage Surgical System",
    category: "Plates & Screws",
    description:
      "Withstand Pressure 15 psi High speed flow rate 900±300ml/min Low speed flow rate 600±300ml/min",
    image: "/img/products/NINGBO Disposable Pulse Lavage Surgical System.jpg", 
    noProduct: "BIK230811",
    modelOrType: "WZ-WS-01-07",
    unitsOfMeasurement: "piece",
    kbkiCode: "4813002042",
    permitToCirculateNumber: "AKL 20902025474",
    factoryName: "NINGBO FIVE CONTINENTS MEDICAL INSTRUMENT CO., LTD.",
    productValidityPeriod: "2025-06-15",
  },
  
  // Produk lain bisa ditambahkan dengan struktur yang sama
];

  